#!/bin/bash
FILES=*

for f in $FILES
do
echo "<div class=\"brick\"><a data-fancybox=\"gallery\" rel=\"group1\" href=\"../images/jaroslavurbanek/$f\"><img class=\"gallery-img\" src=\"../images/jaroslavurbanek/t/$f\"alt=\"\"></a></div>"
done


